export const products = [
  {
    id: 1,
    slug: "gifts-for-him",
    name: "Gifts for Him",
    subtitle: "The Patriarch Collection",
    category: "For Him",
    categoryTag: "FOR HIM",
    tagline:
      "Thoughtfully curated and customized gifts for fathers, husbands, brothers, colleagues, mentors, and other special men.",
    price: 20000,
    priceDisplay: "From ₦20,000",
    badge: "BESTSELLER",
    initial: "G",
    cardColor: "gold",
    images: [
      "/images/products/product_1_photo_1.jpeg",
      "/images/products/product_1_photo_2.jpeg",
      "/images/products/product_1_photo_3.jpeg",
      "/images/products/product_1_photo_4.jpeg",
      "/images/products/product_1_photo_5.jpeg",
      "/images/products/product_1_photo_6.jpeg",
      "/images/products/product_1_photo_7.jpeg",
      "/images/products/product_1_photo_8.jpeg",
      "/images/products/product_1_photo_9.jpeg",
      "/images/products/product_1_photo_10.jpeg",
    ],
    occasions: ["Birthday", "Anniversary", "Graduation", "Corporate"],
    features: ["Custom engraving available", "Gift wrap included", "Nationwide delivery"],
    budgetMin: 20000,
    description:
      "Every man deserves a gift that speaks to who he is. Our Gifts for Him collection is curated with intention — from sleek executive sets to warm personal tokens. Each piece is customisable with his name, initials, or a message that lasts.",
    subItems: [
      "Custom flask & tumbler sets",
      "Personalised leather goods",
      "Watch & accessory sets",
      "Executive desk collections",
      "Branded apparel & grooming kits",
    ],
  },
  {
    id: 2,
    slug: "gifts-for-her",
    name: "Gifts for Her",
    subtitle: "The Fleur & Velvet Collection",
    category: "For Her",
    categoryTag: "FOR HER",
    tagline:
      "Gift collections for mothers, wives, sisters, friends, colleagues, and other special women.",
    price: 20000,
    priceDisplay: "From ₦20,000",
    badge: "CUSTOM",
    initial: "F",
    cardColor: "purple",
    images: [
      "/images/products/product_2_photo_1.jpeg",
      "/images/products/product_2_photo_2.jpeg",
      "/images/products/product_2_photo_3.jpeg",
      "/images/products/product_2_photo_4.jpeg",
      "/images/products/product_2_photo_5.jpeg",
      "/images/products/product_2_photo_6.jpeg",
      "/images/products/product_2_photo_7.jpeg",
      "/images/products/product_2_photo_8.jpeg",
      "/images/products/product_2_photo_9.jpeg",
      "/images/products/product_2_photo_10.jpeg",
    ],
    occasions: ["Birthday", "Anniversary", "Wedding", "Mother's Day", "Valentine's Day"],
    features: ["Custom engraving available", "Luxury packaging", "Nationwide delivery"],
    budgetMin: 20000,
    description:
      "She deserves the extraordinary. Our Gifts for Her collection blends elegance with personality — curated sets that feel personal, presented beautifully. From spa-inspired hampers to personalised keepsakes, every gift tells her she is seen.",
    subItems: [
      "Personalised skincare & spa sets",
      "Custom water bottles & tumblers",
      "Jewellery & accessories",
      "Floral & fragrance collections",
      "Handbag & lifestyle bundles",
    ],
  },
  {
    id: 3,
    slug: "event-souvenirs",
    name: "Event Souvenirs",
    subtitle: "Memories, Gifted",
    category: "Wedding Souvenir",
    categoryTag: "WEDDING SOUVENIR",
    tagline: "Customized souvenirs for celebrations and events.",
    price: 2000,
    priceDisplay: "From ₦2,000",
    badge: "NEW",
    initial: "E",
    cardColor: "cream",
    images: [
      "/images/products/product_3_photo_1.jpeg",
      "/images/products/product_3_photo_2.jpeg",
      "/images/products/product_3_photo_3.jpeg",
      "/images/products/product_3_photo_4.jpeg",
      "/images/products/product_3_photo_5.jpeg",
      "/images/products/product_3_photo_6.jpeg",
      "/images/products/product_3_photo_7.jpeg",
      "/images/products/product_3_photo_8.jpeg",
      "/images/products/product_3_photo_9.jpeg",
      "/images/products/product_3_photo_10.jpeg",
    ],
    occasions: ["Wedding", "Birthday", "Graduation", "Church & Conference"],
    features: ["Minimum order: 20 units", "Custom branding", "Fast turnaround"],
    budgetMin: 2000,
    description:
      "Your event deserves to be remembered. We create beautiful, branded souvenirs that guests keep long after the occasion ends. From intimate dinners to large conferences — we handle every detail so you don't have to.",
    subItems: [
      "Wedding souvenirs (set of 100+)",
      "Birthday keepsakes & favours",
      "Graduation gift sets",
      "Church event souvenirs",
      "Conference & seminar branded items",
    ],
  },
  {
    id: 4,
    slug: "corporate-gifts",
    name: "Corporate Gifts",
    subtitle: "Brand That Gives",
    category: "Corporate",
    categoryTag: "CORPORATE",
    tagline:
      "Products for businesses, organizations, and professional events.",
    price: 7000,
    priceDisplay: "From ₦7,000",
    badge: "BRANDED",
    initial: "C",
    cardColor: "purple-mid",
    images: [
      "/images/products/product_4_photo_1.jpeg",
      "/images/products/product_4_photo_2.jpeg",
      "/images/products/product_4_photo_3.jpeg",
      "/images/products/product_4_photo_4.jpeg",
      "/images/products/product_4_photo_5.jpeg",
      "/images/products/product_4_photo_6.jpeg",
      "/images/products/product_4_photo_7.jpeg",
      "/images/products/product_4_photo_8.jpeg",
      "/images/products/product_4_photo_9.jpeg",
      "/images/products/product_4_photo_10.jpeg",
    ],
    occasions: ["Corporate", "Graduation"],
    features: ["Your logo & branding", "Bulk pricing available", "Nationwide delivery"],
    budgetMin: 7000,
    description:
      "Gifts that carry your brand forward. We create thoughtful, high-quality branded merchandise that represents your organisation with pride. Whether you're rewarding employees, impressing clients, or launching a campaign — we deliver impact.",
    subItems: [
      "Branded gift sets",
      "Employee appreciation gifts",
      "Client & VIP gift hampers",
      "Promotional merchandise",
      "Company-branded stationery & accessories",
    ],
  },
  {
    id: 5,
    slug: "bespoke-consultation",
    name: "Bespoke Consultation",
    subtitle: "Your Vision, Crafted",
    category: "Bespoke",
    categoryTag: "BESPOKE",
    tagline:
      "A dedicated service where clients receive guidance on gift selection, branding solutions, and bespoke gift creation tailored to their needs and budget.",
    price: 0,
    priceDisplay: "Free Consultation",
    badge: null,
    initial: "B",
    cardColor: "gold",
    images: [
      "/images/products/product_5_photo_1.jpeg",
      "/images/products/product_5_photo_2.jpeg",
      "/images/products/product_5_photo_3.jpeg",
      "/images/products/product_5_photo_4.jpeg",
      "/images/products/product_5_photo_5.jpeg",
    ],
    occasions: [],
    features: ["Free initial consultation", "Custom design", "Dedicated advisor"],
    budgetMin: 3000,
    description:
      "Have a vision but need help bringing it to life? Our bespoke consultation service pairs you with a gifting advisor who listens, designs, and executes to perfection. No idea is too big or too personal.",
    subItems: [
      "One-on-one gifting consultation",
      "Custom branding solutions",
      "Budget planning & curation",
      "Corporate gifting strategy",
      "Bespoke gift creation from scratch",
    ],
  },
];

export const occasions = [
  {
    name: "Wedding", count: 128, slug: "wedding", icon: "💍",
    image: "https://images.unsplash.com/photo-1519741497674-611481863552?w=600&q=80&fit=crop&auto=format",
  },
  {
    name: "Birthday", count: 94, slug: "birthday", icon: "🎂",
    image: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600&q=80&fit=crop&auto=format",
  },
  {
    name: "Graduation", count: 52, slug: "graduation", icon: "🎓",
    image: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=600&q=80&fit=crop&auto=format",
  },
  {
    name: "Corporate", count: 76, slug: "corporate", icon: "💼",
    image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=600&q=80&fit=crop&auto=format",
  },
  {
    name: "Anniversary", count: 40, slug: "anniversary", icon: "❤️",
    image: "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?w=600&q=80&fit=crop&auto=format",
  },
  {
    name: "Valentine's Day", count: 45, slug: "valentines", icon: "💝",
    image: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=600&q=80&fit=crop&auto=format",
  },
  {
    name: "Mother's Day", count: 50, slug: "mothers-day", icon: "🌺",
    image: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=600&q=80&fit=crop&auto=format",
  },
  {
    name: "Father's Day", count: 42, slug: "fathers-day", icon: "👔",
    image: "https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=600&q=80&fit=crop&auto=format",
  },
  {
    name: "Baby Shower", count: 35, slug: "baby-shower", icon: "👶",
    image: "https://images.unsplash.com/photo-1519689680058-324335c77eba?w=600&q=80&fit=crop&auto=format",
  },
  {
    name: "Christmas", count: 60, slug: "christmas", icon: "🎄",
    image: "https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=600&q=80&fit=crop&auto=format",
  },
  {
    name: "Church & Conference", count: 30, slug: "church-conference", icon: "⛪",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600&q=80&fit=crop&auto=format",
  },
  {
    name: "Other Occasions", count: 20, slug: "other", icon: "🎁",
    image: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&q=80&fit=crop&auto=format",
  },
];

export const budgetRanges = [
  {
    label: "Under ₦10k",
    description: "Token souvenirs & party favours",
    range: "0-10000",
  },
  {
    label: "₦10k – ₦30k",
    description: "Considered everyday gifts",
    range: "10000-30000",
  },
  {
    label: "₦30k – ₦80k",
    description: "Premium curated sets",
    range: "30000-80000",
  },
  {
    label: "₦80k+",
    description: "Bespoke luxury hampers",
    range: "80000+",
  },
];

export const testimonials = [
  {
    id: 1,
    quote: "Beautifully customized and delivered exactly as promised.",
    detail: "Excellent quality and outstanding customer service.",
    author: "David O.",
    occasion: "Birthday gift",
    initials: "DO",
    orders: null,
  },
  {
    id: 2,
    quote: "They brought my gift idea to life perfectly. Every detail considered.",
    detail: null,
    author: "Samuel I.",
    occasion: "Anniversary gift",
    initials: "SI",
    orders: null,
  },
  {
    id: 3,
    quote: "Quality products, beautiful packaging, and timely delivery — every time.",
    detail: null,
    author: "Jennifer O.",
    occasion: "Repeat client",
    initials: "JO",
    orders: "8 orders",
  },
  {
    id: 4,
    quote: "The recipient loved it! Highly recommended.",
    detail: "The packaging alone was worth it.",
    author: "Grace E.",
    occasion: "Wedding souvenir",
    initials: "GE",
    orders: null,
  },
  {
    id: 5,
    quote: "Professional, reliable, and attention to detail was amazing.",
    detail: null,
    author: "Michael A.",
    occasion: "Corporate gift",
    initials: "MA",
    orders: null,
  },
  {
    id: 6,
    quote: "Great experience from consultation to delivery.",
    detail: null,
    author: "Blessing U.",
    occasion: "Graduation gift",
    initials: "BU",
    orders: null,
  },
];

export const coreValues = [
  {
    roman: "i.",
    name: "Creativity with love",
    description: "Every brief is reimagined from scratch.",
  },
  {
    roman: "ii.",
    name: "Customer delight",
    description: "From first DM to final unwrap.",
  },
  {
    roman: "iii.",
    name: "Trust",
    description: "Promised delivery, kept on time.",
  },
  {
    roman: "iv.",
    name: "Craftmanship",
    description: "Quality that survives the unwrapping.",
  },
];

export const navLinks = [
  { label: "Shop", href: "/shop" },
  { label: "Occasions", href: "/occasions" },
  { label: "Corporate", href: "/corporate" },
  { label: "Bespoke", href: "/bespoke" },
  { label: "About", href: "/about" },
];

export const socialLinks = {
  instagram: "https://www.instagram.com/ol_gifts_souvenirs?igsh=MTBrYzFyanpxOTh3Yw%3D%3D&utm_source=qr",
  tiktok: "https://www.tiktok.com/@ol.gifts.and.souv?_r=1&_t=ZS-97GcAvcfdX3",
  whatsapp: "https://wa.me/2349065049121",
  email: "olgiftssouvenirs@gmail.com",
};
